# Generated by Django 5.2 on 2025-05-02 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('released', models.DateField()),
                ('media', models.CharField(choices=[('Anime', 'Anime'), ('Movies', 'Movies'), ('TV_series', 'TV_series')], max_length=10)),
                ('genre', models.CharField(choices=[('action', 'action'), ('psychological', 'psychological'), ('comedy', 'comedy'), ('romance', 'romance'), ('sci-fi', 'sci-fi'), ('cyberpunk', 'cyberpunk')], max_length=30)),
                ('director', models.CharField(max_length=250)),
                ('poster', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
