# Generated by Django 5.2 on 2025-04-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=models.URLField(max_length=500),
        ),
    ]
