# Generated by Django 5.2 on 2025-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
