# Generated by Django 5.2 on 2025-05-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_rating_downvotes_rating_upvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='released',
            new_name='release_date',
        ),
    ]
