# Generated by Django 5.2 on 2025-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_rename_released_media_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.CharField(default='Theres nothing here...', max_length=1000),
        ),
    ]
