# Generated by Django 5.2 on 2025-05-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_media_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(default='(This guy wrote nothing)'),
        ),
    ]
