# Generated by Django 5.2 on 2025-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(default="<i style='color:grey;'>(This guy wrote nothing)</i>"),
        ),
    ]
