# Generated by Django 5.2 on 2025-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_hanekawa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, default='(This guy wrote nothing)', null=True),
        ),
    ]
